### ISSUE TITLE
Get only username

### ISSUE THREAD

**Issue by edanko** [quasoft/websspi#2]
Hi, quasoft! 
It's not an issue, but a question. 
It is possible to get only the user name and do not perform auth? I do not have access to domain controller and can't add user to AD.

**Comment by quasoft** [comment]
Sorry, it's not possible as this is the main purpose of this module.

If you don't want to use AD may be you should look for another authentication middleware that uses external services to authenticate requests (eg. with Google, Facebook accounts).
